kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: syncloadtest
  name: service-reader
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["namespaces","pods","services"]
  verbs: ["get", "watch", "list"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: service-reader
subjects:
- kind: ServiceAccount
  name: default
  namespace: syncloadtest
roleRef:
  kind: ClusterRole
  name: service-reader
  apiGroup: rbac.authorization.k8s.io
